version: "3.9"
services:
  tsunami:
    restart: always
    build: ./tsunami-security-scanner
    network_mode: host
    volumes:
      - ./logs:/usr/tsunami/logs
  jupyter:
    image: "jupyter/base-notebook"
    command: "start-notebook.sh --NotebookApp.token=''"
    ports:
        - "8888:8888"
  flask:
    restart: always
    build: ./flask
    ports:
        - "5000:5000"
    volumes:
        - ./flask:/code
    depends_on:
        - redis
  redis:
    image: redis
  alert-manager:
    restart: always
    build: ./alertManager
    volumes:
      - ./logs:/usr/tsunami/logs
      - ./alertManager:/code
   
